# Generated by Django 5.0.1 on 2025-04-14 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegTBL',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('mob_no', models.CharField(max_length=20)),
                ('id_proof', models.TextField()),
                ('email_id_customer', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerRegTBL',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('mob_no', models.CharField(max_length=20)),
                ('email_id_owner', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('license_document', models.FileField(blank=True, null=True, upload_to='licenses/')),
                ('company_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShopTBL',
            fields=[
                ('upi', models.CharField(max_length=30, unique=True)),
                ('shop_name', models.CharField(max_length=50)),
                ('mob_no', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('id_proof', models.CharField(max_length=50)),
                ('email_id_shop', models.EmailField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTBL',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.FloatField()),
                ('items', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('email_id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.customerregtbl')),
            ],
        ),
        migrations.CreateModel(
            name='StaffTBL',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('mob_no', models.CharField(max_length=20)),
                ('id_proof', models.TextField()),
                ('email_id_staff', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('upi', models.CharField(max_length=30)),
                ('wage', models.FloatField()),
                ('assigned_to', models.CharField(max_length=20)),
                ('staff_type', models.CharField(max_length=20)),
                ('email_id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.ownerregtbl')),
                ('email_id_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.shoptbl')),
            ],
        ),
    ]
