# Generated by Django 5.2 on 2025-04-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0002_customerregtbl_ownerregtbl_shoptbl_servicetbl_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownerregtbl",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
