# Generated by Django 5.2 on 2025-04-14 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0003_alter_ownerregtbl_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicetbl",
            name="email_id_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Admin.ownerregtbl"
            ),
        ),
    ]
