# Generated by Django 5.2 on 2025-04-14 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0004_alter_servicetbl_email_id_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingTBL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                ("items", models.CharField(max_length=50)),
                ("rate", models.FloatField()),
                ("Approvalstatus", models.IntegerField(default=0)),
                ("PaymentStatus", models.IntegerField(default=0)),
                ("WorkCompletedSts", models.IntegerField(default=0)),
                ("assigned_team", models.CharField(max_length=50)),
                (
                    "email_id_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admin.customerregtbl",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admin.servicetbl",
                    ),
                ),
            ],
        ),
    ]
