# Generated by Django 5.2 on 2025-04-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0005_bookingtbl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingtbl",
            name="assigned_team",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bookingtbl",
            name="items",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bookingtbl",
            name="rate",
            field=models.FloatField(null=True),
        ),
    ]
