# Generated by Django 5.2 on 2025-04-15 07:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0006_alter_bookingtbl_assigned_team_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustOwnerChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=500)),
                ("sts", models.IntegerField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "bookingid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admin.bookingtbl",
                    ),
                ),
            ],
        ),
    ]
