# Generated by Django 5.2 on 2025-04-15 07:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0007_custownerchat"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackTBL",
            fields=[
                ("feedback_id", models.AutoField(primary_key=True, serialize=False)),
                ("feedback", models.TextField()),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "email_id_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admin.customerregtbl",
                    ),
                ),
            ],
        ),
    ]
