# Generated by Django 5.2 on 2025-04-15 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0008_feedbacktbl"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbacktbl",
            name="bookingid",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Admin.bookingtbl",
            ),
            preserve_default=False,
        ),
    ]
