# Generated by Django 5.2 on 2025-04-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0010_managerstaffchat"),
    ]

    operations = [
        migrations.AddField(
            model_name="managerstaffchat",
            name="staff_email",
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
